version: 2
updates:
  - package-ecosystem: npm
    directory: "/packages/metals-languageclient"
    schedule:
      interval: daily
    open-pull-requests-limit: 2
  - package-ecosystem: npm
    directory: "/packages/metals-vscode"
    schedule:
      interval: daily
    open-pull-requests-limit: 2
